FROM rust:bookworm AS builder

WORKDIR /src

COPY Cargo.toml Cargo.lock ./
COPY crates ./crates
COPY apps ./apps

RUN cargo build --release -p quippi

FROM debian:bookworm-slim

COPY --from=builder /src/target/release/quippi /usr/local/bin/quippi

ENTRYPOINT ["/usr/local/bin/quippi"]
